management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true


springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false